places = ['jiu zhai gou', 'huang shan', 'hua shan', 'xi zang', 'si chuan']
print(places)
print(sorted(places))
print(places)
print(sorted(places, reverse=True))
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)